### PR TITLE
TLS support - fix issue #23

### LINKED ISSUE #2: Project description has a misspelling
One of these things is not like the other :wink:
screencap

I had to double check myself.

### PR DESCRIPTION
**Pull request by nukemberg**

### CODE REVIEW

**Comment by jamtur01** [comment]
Some other ideas:

1. Docs/README update.
2. Tests?

**Comment by smortex** [comment]
FYI, I just opened #32 that setup GitHub actions to run the tests in CI and fix them.  When merged, my next step will be to add tests for TLS transport on top of these changes.

**Comment by smortex** [comment]
See #33 which takes this code and integrate CI to test it.

**Comment by jamtur01** [comment]
Closing in favour of #33 - thanks @nukemberg for getting this started!

**Pull request closed without merging**
